CREATE TABLE `address` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `IdCity` int DEFAULT NULL,
  `IdCityStreet` int DEFAULT NULL,
  `City` varchar(50) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
  `Street` varchar(70) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `Number` varchar(20) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
  `ZipCode` varchar(6) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
  `Commune` varchar(50) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
  `District` varchar(50) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
  `State` varchar(20) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
  `Lat` decimal(8,6) NOT NULL,
  `Lon` decimal(8,6) NOT NULL,
  `CityStreet` varchar(120) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `LatShort2` tinyint DEFAULT NULL,
  `LonShort2` tinyint DEFAULT NULL,
  `LatShort3` smallint DEFAULT NULL,
  `LonShort3` smallint DEFAULT NULL,
  `LatShort4` smallint DEFAULT NULL,
  `LonShort4` smallint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `Idx_IdCity` (`IdCity`),
  KEY `Idx_IdCityStreet` (`IdCityStreet`),
  KEY `Idx_LatShort` (`LatShort2`) USING BTREE,
  KEY `Idx_LonShort` (`LonShort2`) USING BTREE,
  KEY `Idx_LatShort3` (`LatShort3`),
  KEY `Idx_LonShort3` (`LonShort3`),
  KEY `Idx_LatShort4` (`LatShort4`),
  KEY `Idx_lonShort4` (`LonShort4`),
  FULLTEXT KEY `Idx_CityStreet` (`CityStreet`),
  FULLTEXT KEY `Idx_Number` (`Number`)
) ENGINE=MyISAM AUTO_INCREMENT=7827685 DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci