CREATE TABLE `place` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `IdClient` int NOT NULL DEFAULT '0',
  `IdAddress` int NOT NULL DEFAULT '0',
  `IdPlaceGroup` int NOT NULL DEFAULT '0',
  `Lat` decimal(8,6) NOT NULL DEFAULT '0.000000',
  `Lon` decimal(8,6) NOT NULL DEFAULT '0.000000',
  `LatShort3` smallint NOT NULL DEFAULT '0',
  `LonShort3` smallint NOT NULL DEFAULT '0',
  `LatShort2` tinyint NOT NULL DEFAULT '0',
  `LonShort2` tinyint NOT NULL DEFAULT '0',
  `IsOwnDelivery` tinyint NOT NULL DEFAULT '0',
  `IsYammyPoint` tinyint NOT NULL DEFAULT '0',
  `IsPromotions` tinyint unsigned NOT NULL DEFAULT '0',
  `IsTables` tinyint NOT NULL DEFAULT '0',
  `IsTakeaway` tinyint NOT NULL DEFAULT '0',
  `IsReservation` tinyint NOT NULL DEFAULT '0',
  `TimeOpenMon` smallint NOT NULL DEFAULT '0',
  `TimeOpenTue` smallint NOT NULL DEFAULT '0',
  `TimeOpenWed` smallint NOT NULL DEFAULT '0',
  `TimeOpenThu` smallint NOT NULL DEFAULT '0',
  `TimeOpenFri` smallint NOT NULL DEFAULT '0',
  `TimeOpenSat` smallint NOT NULL DEFAULT '0',
  `TimeOpenSun` smallint NOT NULL DEFAULT '0',
  `TimeCloseMon` smallint NOT NULL DEFAULT '0',
  `TimeCloseTue` smallint NOT NULL DEFAULT '0',
  `TimeCloseWed` smallint NOT NULL DEFAULT '0',
  `TimeCloseThu` smallint NOT NULL DEFAULT '0',
  `TimeCloseFri` smallint NOT NULL DEFAULT '0',
  `TimeCloseSat` smallint NOT NULL DEFAULT '0',
  `TimeCloseSun` smallint NOT NULL DEFAULT '0',
  `Name` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `TagFoodType` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `Descrip` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `Street` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `Post` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `City` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `Email` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `Phone` varchar(16) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `Rating` decimal(13,12) DEFAULT NULL,
  `RatingCount` int DEFAULT NULL,
  `Rating1` int DEFAULT NULL,
  `Rating2` int DEFAULT NULL,
  `Rating3` int DEFAULT NULL,
  `Rating4` int DEFAULT NULL,
  `Rating5` int DEFAULT NULL,
  `LikedToday` int DEFAULT NULL,
  `LikedLast1` int DEFAULT NULL,
  `LikedLast3` int DEFAULT NULL,
  `LikedLast7` int DEFAULT NULL,
  `LikedLast30` int DEFAULT NULL,
  `PopularToday` int DEFAULT NULL,
  `PopularLast1` int DEFAULT NULL,
  `PopularLast3` int DEFAULT NULL,
  `PopularLast7` int DEFAULT NULL,
  `PopularLast30` int DEFAULT NULL,
  `PopularTotal` int DEFAULT NULL,
  `PriceRange` tinyint DEFAULT NULL,
  `PriceAvg` tinyint DEFAULT NULL,
  `DeliveryTimeMin` smallint DEFAULT NULL,
  `DeliveryTimeMax` smallint DEFAULT NULL,
  `DeliveryPrice` decimal(4,2) DEFAULT NULL,
  `ModifiedActivity` timestamp NULL DEFAULT NULL,
  `ModifiedPromo` timestamp NULL DEFAULT NULL,
  `ModifiedMenu` timestamp NULL DEFAULT NULL,
  `ModifiedRating` timestamp NULL DEFAULT NULL,
  `ModifiedPicture` timestamp NULL DEFAULT NULL,
  `ModifiedReview` timestamp NULL DEFAULT NULL,
  `Created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `PictureUrl` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MinDeliveryCost` int DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `Idx_LatShort2` (`LatShort2`),
  KEY `Idx_LonShort2` (`LonShort2`),
  KEY `Idx_LatShort3` (`LatShort3`),
  KEY `Idx_LonShort3` (`LonShort3`),
  FULLTEXT KEY `Idx_Name` (`Name`)
) ENGINE=InnoDB AUTO_INCREMENT=2049 DEFAULT CHARSET=utf8 COLLATE=utf8_bin