CREATE TABLE `promo` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `IdClient` int NOT NULL DEFAULT '0',
  `IdPlace` int NOT NULL DEFAULT '0',
  `IdWall` int NOT NULL DEFAULT '0',
  `Title` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `Descrip` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `PictureLink` varchar(128) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `isExpired` tinyint DEFAULT NULL,
  `isVisible` tinyint DEFAULT NULL,
  `ValidTo` datetime DEFAULT NULL,
  `PlaceLat` decimal(10,8) DEFAULT NULL,
  `PlaceLon` decimal(10,8) DEFAULT NULL,
  `PlaceLatShort3` smallint DEFAULT NULL,
  `PlaceLonShort3` smallint DEFAULT NULL,
  `Created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ValidFrom` datetime DEFAULT NULL,
  `Form` enum('image','qrcode','barcode') COLLATE utf8_polish_ci DEFAULT NULL,
  `Type` enum('oneTime','manyTime') COLLATE utf8_polish_ci DEFAULT NULL,
  `TimeForUse` int DEFAULT NULL,
  `HeaderLink` varchar(128) COLLATE utf8_polish_ci DEFAULT NULL,
  `CodeLink` varchar(128) COLLATE utf8_polish_ci DEFAULT NULL,
  `DescripLink` varchar(128) COLLATE utf8_polish_ci DEFAULT NULL,
  `HomePage` tinyint NOT NULL DEFAULT '0',
  `DeletedAt` datetime DEFAULT NULL,
  `Premium` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `Idx_IdClient` (`IdClient`) USING BTREE,
  KEY `Idx_IdWall` (`IdWall`),
  KEY `Idx_IdLocation` (`IdPlace`) USING BTREE,
  KEY `Idx_LocationLat` (`PlaceLat`) USING BTREE,
  KEY `Idx_LocationLon` (`PlaceLon`) USING BTREE,
  KEY `Idx_LocationLat3` (`PlaceLatShort3`) USING BTREE,
  KEY `Idx_LocationLon3` (`PlaceLonShort3`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=68151 DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci