CREATE TABLE `user` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `IdFirstLocation` int DEFAULT NULL,
  `IdPlace` int DEFAULT NULL,
  `IdDeliveryLast` int DEFAULT NULL,
  `AuthenticationType` tinyint DEFAULT NULL,
  `PushMaxPerDay` tinyint NOT NULL DEFAULT '5',
  `PushSendToday` tinyint NOT NULL DEFAULT '0',
  `Points` mediumint DEFAULT '0',
  `LoginLast` timestamp NULL DEFAULT NULL,
  `LoginAttempt` tinyint DEFAULT NULL,
  `LoginIsAccountLocked` tinyint NOT NULL DEFAULT '0',
  `photo` varchar(255) DEFAULT NULL,
  `role` varchar(255) NOT NULL DEFAULT 'user',
  `active` tinyint DEFAULT NULL,
  `deletedAt` datetime(6) DEFAULT NULL,
  `Email` varchar(255) DEFAULT NULL,
  `EmailPassHash` varchar(255) DEFAULT NULL,
  `Phone` varchar(255) DEFAULT NULL,
  `FCMToken` varchar(255) DEFAULT NULL,
  `FCMId` varchar(255) DEFAULT NULL,
  `FacebookId` varchar(255) DEFAULT NULL,
  `GoogleId` varchar(255) DEFAULT NULL,
  `PasswordRecoveryToken` varchar(255) DEFAULT NULL,
  `FirstName` varchar(255) DEFAULT NULL,
  `LastName` varchar(255) DEFAULT NULL,
  `PushLastDate` datetime DEFAULT NULL,
  `LastActivity` datetime DEFAULT NULL,
  `Created` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `Modified` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `email` (`Email`),
  KEY `facebook_id` (`FacebookId`) /*!80000 INVISIBLE */,
  KEY `google_id` (`GoogleId`) /*!80000 INVISIBLE */,
  KEY `phone` (`Phone`)
) ENGINE=InnoDB AUTO_INCREMENT=1400114 DEFAULT CHARSET=utf8 COMMENT='AuthenticationType: 1=email, 2=phone, 3=google, 4=facebook'